# ============================================================================
#  rewrite-html.ps1
#  Updates index.html to use the optimised media generated by optimize-media.ps1.
#
#  - <img src="images/image-web/X.jpg"> -> <picture><source webp srcset>...</picture>
#  - <video src="X.mp4"> -> <video poster><source webm><source opt.mp4></video>
#
#  NON-DESTRUCTIVE: makes a timestamped backup of index.html first.
#  Only rewrites tags whose optimised siblings actually exist on disk.
# ============================================================================

[CmdletBinding()]
param(
    [string]$HtmlFile = (Join-Path $PSScriptRoot 'index.html'),
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
$Root = Split-Path $HtmlFile -Parent
if (-not (Test-Path -LiteralPath $HtmlFile)) {
    throw "index.html not found at $HtmlFile"
}

# Backup
$backup = $HtmlFile + ".backup-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
if (-not $DryRun) {
    Copy-Item -LiteralPath $HtmlFile -Destination $backup
    Write-Host "Backup saved: $backup" -ForegroundColor Green
}

$html = Get-Content -LiteralPath $HtmlFile -Raw -Encoding UTF8
$original = $html

$imgRewrites = 0
$imgSkipped  = 0
$videoRewrites = 0
$videoSkipped  = 0

# ---------------------------------------------------------------------------
# IMAGE REWRITER
# Match: <img ... src="images/image-web/FILE.jpg" ... />   (self-closing or not)
# Skips: anything in images/image-abiliti/ (logos, banner) - too small to benefit
# ---------------------------------------------------------------------------
$imgPattern = '<img\b([^>]*?)\s+src="(images/image-web/([^"]+?)\.(jpg|jpeg|png))"([^>]*?)\s*/?>'

$html = [regex]::Replace($html, $imgPattern, {
    param($m)
    $attrsBefore = $m.Groups[1].Value
    $fullSrc     = $m.Groups[2].Value
    $stem        = $m.Groups[3].Value
    $ext         = $m.Groups[4].Value
    $attrsAfter  = $m.Groups[5].Value

    $imgDir = Join-Path $Root 'images/image-web'
    $webp480  = Join-Path $imgDir ("{0}-480w.webp"  -f $stem)
    $webp960  = Join-Path $imgDir ("{0}-960w.webp"  -f $stem)
    $webp1440 = Join-Path $imgDir ("{0}-1440w.webp" -f $stem)

    $haveAny = (Test-Path -LiteralPath $webp480) -or `
               (Test-Path -LiteralPath $webp960) -or `
               (Test-Path -LiteralPath $webp1440)
    if (-not $haveAny) {
        $script:imgSkipped++
        return $m.Value  # leave untouched
    }

    # Build srcset from whatever widths exist
    $entries = @()
    if (Test-Path -LiteralPath $webp480)  { $entries += "images/image-web/${stem}-480w.webp 480w"  }
    if (Test-Path -LiteralPath $webp960)  { $entries += "images/image-web/${stem}-960w.webp 960w"  }
    if (Test-Path -LiteralPath $webp1440) { $entries += "images/image-web/${stem}-1440w.webp 1440w" }
    $webpSrcset = $entries -join ', '

    # Preserve all original attributes on the inner <img>
    $innerAttrs = ($attrsBefore + ' ' + $attrsAfter).Trim() -replace '\s+', ' '

    $script:imgRewrites++
    return @"
<picture><source type="image/webp" srcset="$webpSrcset" sizes="(max-width: 768px) 100vw, 50vw"><img $innerAttrs src="$fullSrc" /></picture>
"@
})

# Also handle images in image-abiliti for the footer banner (large) only
$bannerPattern = '<img\b([^>]*?)\s+src="(images/image-abiliti/baniere\.png)"([^>]*?)\s*/?>'
$html = [regex]::Replace($html, $bannerPattern, {
    param($m)
    $attrsBefore = $m.Groups[1].Value
    $fullSrc     = $m.Groups[2].Value
    $attrsAfter  = $m.Groups[3].Value
    $stem = 'baniere'

    $imgDir = Join-Path $Root 'images/image-abiliti'
    $webp480  = Join-Path $imgDir ("{0}-480w.webp"  -f $stem)
    $webp960  = Join-Path $imgDir ("{0}-960w.webp"  -f $stem)
    $webp1440 = Join-Path $imgDir ("{0}-1440w.webp" -f $stem)

    $entries = @()
    if (Test-Path -LiteralPath $webp480)  { $entries += "images/image-abiliti/${stem}-480w.webp 480w" }
    if (Test-Path -LiteralPath $webp960)  { $entries += "images/image-abiliti/${stem}-960w.webp 960w" }
    if (Test-Path -LiteralPath $webp1440) { $entries += "images/image-abiliti/${stem}-1440w.webp 1440w" }
    if ($entries.Count -eq 0) { $script:imgSkipped++; return $m.Value }
    $webpSrcset = $entries -join ', '

    $innerAttrs = ($attrsBefore + ' ' + $attrsAfter).Trim() -replace '\s+', ' '
    $script:imgRewrites++
    return @"
<picture><source type="image/webp" srcset="$webpSrcset" sizes="(max-width: 768px) 100vw, 100vw"><img $innerAttrs src="$fullSrc" /></picture>
"@
})

# ---------------------------------------------------------------------------
# VIDEO REWRITER
# Match: <video ... src="X.mp4" ... ></video>
# Output: <video ... poster="..." ...><source webm><source opt.mp4></video>
# ---------------------------------------------------------------------------
$videoPattern = '<video\b([^>]*?)\s+src="([^"]+?\.mp4)"([^>]*?)>\s*</video>'

$html = [regex]::Replace($html, $videoPattern, {
    param($m)
    $attrsBefore = $m.Groups[1].Value
    $srcMp4      = $m.Groups[2].Value
    $attrsAfter  = $m.Groups[3].Value

    # Resolve disk path of the original mp4 (relative to project root)
    $srcDisk = Join-Path $Root ($srcMp4 -replace '/', '\')
    $srcDir  = Split-Path $srcDisk -Parent
    $srcStem = [System.IO.Path]::GetFileNameWithoutExtension($srcDisk)

    $webmDisk = Join-Path $srcDir ($srcStem + '.webm')
    $optDisk  = Join-Path $srcDir ($srcStem + '.opt.mp4')
    $posterDisk = Join-Path $srcDir ($srcStem + '.poster.jpg')

    # Build relative web paths (forward slashes)
    $relDir = Split-Path $srcMp4 -Parent
    if ($relDir) { $relDir = $relDir.TrimEnd('/') + '/' } else { $relDir = '' }
    $webmRel = $relDir + $srcStem + '.webm'
    $optRel  = $relDir + $srcStem + '.opt.mp4'
    $posterRel = $relDir + $srcStem + '.poster.jpg'

    $haveOpt  = Test-Path -LiteralPath $optDisk
    $haveWebm = Test-Path -LiteralPath $webmDisk
    $havePoster = Test-Path -LiteralPath $posterDisk

    if (-not $haveOpt -and -not $haveWebm) {
        $script:videoSkipped++
        return $m.Value
    }

    # Preserve existing attributes (muted, playsinline, loop, preload, poster, etc.)
    # If no poster already on the tag, inject one if we have the generated poster.
    $allAttrs = ($attrsBefore + ' ' + $attrsAfter).Trim() -replace '\s+', ' '

    if ($allAttrs -notmatch '\bposter\s*=') {
        if ($havePoster) {
            $allAttrs += ' poster="' + $posterRel + '"'
        }
    }

    $sources = @()
    if ($haveWebm) { $sources += '<source src="' + $webmRel + '" type="video/webm">' }
    if ($haveOpt)  { $sources += '<source src="' + $optRel  + '" type="video/mp4">' }
    # Always keep an MP4 fallback for clients that ignore <source>:
    # add the original src on the inner element via a final <source>
    $sources += '<source src="' + $srcMp4 + '" type="video/mp4">'

    $script:videoRewrites++
    return @"
<video $allAttrs>
  $($sources -join "`n  ")
</video>
"@
})

# ---------------------------------------------------------------------------
# SAVE
# ---------------------------------------------------------------------------
$changed = ($html -ne $original)

Write-Host ""
Write-Host "===== rewrite-html.ps1 summary =====" -ForegroundColor Cyan
Write-Host (" Image rewrites : {0}" -f $imgRewrites)
Write-Host (" Images skipped : {0} (no optimised siblings)" -f $imgSkipped)
Write-Host (" Video rewrites : {0}" -f $videoRewrites)
Write-Host (" Videos skipped : {0}" -f $videoSkipped)
Write-Host (" Changed        : {0}" -f $changed)

if ($DryRun) {
    Write-Host " (DRY RUN - file not written)" -ForegroundColor Yellow
    return
}

if ($changed) {
    Set-Content -LiteralPath $HtmlFile -Value $html -Encoding UTF8 -NoNewline
    Write-Host " Wrote: $HtmlFile" -ForegroundColor Green
} else {
    Write-Host " No changes to write." -ForegroundColor Yellow
}
